//! Projection definition code generator.
//!
//! One JSON definition document declares a project's entities, projections,
//! mutations and collaborative document layouts. This crate validates it and
//! generates, from it alone, the Rust model module, the TypeScript model
//! module, the normalised IR and both fixture corpora.
//!
//! The generator accepts only the JSON Schema subset its renderers represent
//! exactly, and refuses a definition that would need a wider or ambiguous
//! generated type.

mod collate;
mod config;
mod definition;
mod error;
mod expand;
mod fixtures;
mod json;
mod layout;
mod names;
mod normalize;
mod rust;
mod schema;
mod schema_imports;
mod typescript;
mod validate;

use std::path::{Path, PathBuf};

pub use config::{Config, OutputPaths, Project};
pub use definition::Definition;
pub use error::{Error, Result};

/// The contents of every generated artefact.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedOutputs {
    pub collaboration_fixtures: String,
    pub contract_fixtures: String,
    pub normalized_definition: String,
    pub typescript_model: String,
    pub rust_model: String,
}

impl GeneratedOutputs {
    /// Each artefact beside the path it is written to.
    pub fn with_paths<'a>(&'a self, paths: &'a OutputPaths) -> [(&'a Path, &'a str); 5] {
        [
            (&paths.collaboration_fixtures, &self.collaboration_fixtures),
            (&paths.contract_fixtures, &self.contract_fixtures),
            (&paths.normalized_definition, &self.normalized_definition),
            (&paths.typescript_model, &self.typescript_model),
            (&paths.rust_model, &self.rust_model),
        ]
        .map(|(path, content)| (path.as_path(), content.as_str()))
    }
}

/// The generated-code header: the configured lines, then the generated notice.
pub(crate) fn header_lines(project: &Project) -> Vec<String> {
    let mut lines = project.header.clone();
    if !lines.is_empty() {
        lines.push(String::new());
    }
    lines.push(format!("Generated by `{}`.", project.regenerate_command));
    lines.push("Do not edit this file by hand.".to_owned());
    lines
}

/// Renders every artefact without touching the filesystem.
pub fn build_outputs(definition: &Definition, config: &Config) -> Result<GeneratedOutputs> {
    let project = &config.project;
    let collaboration_fixtures = fixtures::render_collaboration_fixtures(definition)?;
    let contract_fixtures = fixtures::render_contract_fixtures(definition)?;
    let normalized_definition = normalize::render_normalized_definition(definition);
    let rust_model = rust::render_model_module(definition, project)?;
    let typescript_model = typescript::render_model_module(definition, project)?;
    Ok(GeneratedOutputs {
        collaboration_fixtures,
        contract_fixtures,
        normalized_definition,
        typescript_model,
        rust_model,
    })
}

/// Whether a run writes the artefacts or only compares them.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Mode {
    /// Write every artefact whose content changed, creating directories.
    Write,
    /// Write nothing; refuse with every stale or missing artefact listed.
    Check,
}

/// Loads the definition `config` names, renders it, and writes or checks the
/// artefacts. Returns the paths whose content changed.
pub fn generate(config: &Config, mode: Mode) -> Result<Vec<PathBuf>> {
    let definition = Definition::load_with_schemas(&config.definition, &config.schema_imports)?;
    let outputs = build_outputs(&definition, config)?;
    let mut changed = Vec::new();
    for (path, content) in outputs.with_paths(&config.outputs) {
        if read_existing(path)?.as_deref() == Some(content.as_bytes()) {
            continue;
        }
        changed.push(path.to_owned());
        if mode == Mode::Write {
            write(path, content)?;
        }
    }
    if mode == Mode::Check && !changed.is_empty() {
        return Err(Error::Stale {
            command: config.project.regenerate_command.clone(),
            paths: changed,
        });
    }
    Ok(changed)
}

/// A missing artefact is stale, not an error.
fn read_existing(path: &Path) -> Result<Option<Vec<u8>>> {
    match std::fs::read(path) {
        Ok(bytes) => Ok(Some(bytes)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(source) => Err(Error::Read {
            path: path.to_owned(),
            source,
        }),
    }
}

fn write(path: &Path, content: &str) -> Result<()> {
    let failed = |source| Error::Write {
        path: path.to_owned(),
        source,
    };
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        std::fs::create_dir_all(parent).map_err(failed)?;
    }
    std::fs::write(path, content).map_err(failed)
}

/// The generator's internals, for Clerkenwell's own tests.
#[cfg(feature = "testing")]
pub mod testing {
    pub use crate::collate::locale_compare;
    pub use crate::json::{number_to_string, Json, Object};
    pub use crate::normalize::normalized_document;
    pub use crate::validate::{schema_keywords, META_SCHEMA};
    use crate::{Definition, Result};

    /// Validates `document` as [`Definition::load`] validates a file.
    pub fn definition(document: Json) -> Result<Definition> {
        Definition::from_json(document)
    }

    /// The document `definition` holds, with the declarations its
    /// collaboration section implies.
    pub fn document(definition: &Definition) -> &Object {
        definition.document()
    }
}
