//! SPDX-License-Identifier: MIT
//!
//! Generated by `cargo run -p clerkenwell-codegen -- --config examples/notes/clerkenwell-codegen.json`.
//! Do not edit this file by hand.

pub use clerkenwell_schema::{
    GeneratedAuthoringConflictPolicy, GeneratedAuthoringPolicyKind, GeneratedCollaborationConflict,
    GeneratedCollaborationEntitySpec, GeneratedCollaborationFieldSpec,
    GeneratedCollaborationStorageKind, GeneratedCollaborationValueCodec,
    GeneratedEntityAuthoringSpec, GeneratedMaterializationPlan, GeneratedMutationSpec,
    GeneratedProjectionSpec, GeneratedRemoveMode, GeneratedSnapshotMode,
};
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq, Eq)]
pub enum NoteDocumentStatus {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "review")]
    Review,
    #[serde(rename = "published")]
    Published,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq, Eq)]
pub enum NoteAuthoringStateExchangeModes {
    #[serde(rename = "incremental")]
    Incremental,
    #[serde(rename = "bootstrap")]
    Bootstrap,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq, Eq)]
pub enum NoteAuthoringStatePatchKind {
    #[serde(rename = "replace")]
    Replace,
    #[serde(rename = "remove")]
    Remove,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq, Eq)]
pub enum LoroUpdateParamsExchangeMode {
    #[serde(rename = "incremental")]
    Incremental,
    #[serde(rename = "bootstrap")]
    Bootstrap,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoteDocument {
    pub note_id: String,
    pub etag: String,
    #[schemars(length(min = 1))]
    pub title: String,
    pub body: String,
    pub status: NoteDocumentStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoteKeyParams {
    pub note_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoteAuthoringState {
    pub note_id: String,
    pub etag: String,
    pub exchange_modes: Vec<NoteAuthoringStateExchangeModes>,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoteAuthoringStatePatch {
    pub kind: NoteAuthoringStatePatchKind,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<NoteAuthoringState>,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoteCreateParams {
    #[schemars(length(min = 1))]
    pub title: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoteMutationResult {
    pub note_id: String,
    pub etag: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct LoroUpdateParams {
    pub note_id: String,
    #[schemars(length(min = 1))]
    pub update: String,
    pub exchange_mode: LoroUpdateParamsExchangeMode,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct SessionDrafts {
    pub drafts: HashMap<String, DraftEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct DraftEntry {
    pub entity: String,
    pub entity_id: String,
    pub saved_at: String,
    pub payload: JsonValue,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct LoroUpdateResult {
    pub etag: String,
}

pub const NOTE_ENTITY: &str = "Note";

pub const NOTES_AUTHORING_STATE_PROJECTION: &str = "notes.authoringState";

pub const NOTE_CREATE_MUTATION: &str = "note.create";
pub const NOTE_IMPORT_LORO_UPDATE_MUTATION: &str = "note.importLoroUpdate";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ProjectionName {
    NotesAuthoringState,
}

#[rustfmt::skip]
impl ProjectionName {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::NotesAuthoringState => {
                NOTES_AUTHORING_STATE_PROJECTION
            },
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            NOTES_AUTHORING_STATE_PROJECTION => {
                Some(Self::NotesAuthoringState)
            },
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MutationName {
    NoteCreate,
    NoteImportLoroUpdate,
}

#[rustfmt::skip]
impl MutationName {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::NoteCreate => {
                NOTE_CREATE_MUTATION
            },
            Self::NoteImportLoroUpdate => {
                NOTE_IMPORT_LORO_UPDATE_MUTATION
            },
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            NOTE_CREATE_MUTATION => {
                Some(Self::NoteCreate)
            },
            NOTE_IMPORT_LORO_UPDATE_MUTATION => {
                Some(Self::NoteImportLoroUpdate)
            },
            _ => None,
        }
    }
}

pub const ENTITY_NAMES: &[&str] = &["Note"];
pub const PROJECTION_NAMES: &[&str] = &["notes.authoringState"];
pub const MUTATION_NAMES: &[&str] = &["note.create", "note.importLoroUpdate"];
pub const SESSION_DRAFTS_MNEMONIC_KEY: &str = "notes.session.drafts";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "projection", content = "value", deny_unknown_fields)]
#[allow(clippy::large_enum_variant)]
pub enum ProjectionTransportSnapshot {
    #[serde(rename = "notes.authoringState")]
    NotesAuthoringState(NoteAuthoringState),
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "projection", content = "value", deny_unknown_fields)]
#[allow(clippy::large_enum_variant)]
pub enum ProjectionTransportPatch {
    #[serde(rename = "notes.authoringState")]
    NotesAuthoringState(NoteAuthoringStatePatch),
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "mutation", content = "value", deny_unknown_fields)]
#[allow(clippy::large_enum_variant)]
pub enum ProjectionTransportMutationResult {
    #[serde(rename = "note.create")]
    NoteCreate(NoteMutationResult),
    #[serde(rename = "note.importLoroUpdate")]
    NoteImportLoroUpdate(LoroUpdateResult),
}

impl ProjectionTransportMutationResult {
    pub const fn mutation_name(&self) -> MutationName {
        match self {
            Self::NoteCreate(_) => MutationName::NoteCreate,
            Self::NoteImportLoroUpdate(_) => MutationName::NoteImportLoroUpdate,
        }
    }
}

pub static GENERATED_PROJECTION_SPECS: &[GeneratedProjectionSpec] = &[GeneratedProjectionSpec {
    name: NOTES_AUTHORING_STATE_PROJECTION,
    depends_on: &["Note"],
    materialization: GeneratedMaterializationPlan::ReplaceOrRemove {
        snapshot_mode: GeneratedSnapshotMode::Field("state"),
        snapshot_omit_fields: &[],
        remove_mode: GeneratedRemoveMode::NullSnapshot,
        update_fields: None,
    },
}];

pub static GENERATED_MUTATION_SPECS: &[GeneratedMutationSpec] = &[
    GeneratedMutationSpec {
        name: NOTE_CREATE_MUTATION,
        touches: &["Note"],
    },
    GeneratedMutationSpec {
        name: NOTE_IMPORT_LORO_UPDATE_MUTATION,
        touches: &["Note"],
    },
];

pub static GENERATED_ENTITY_AUTHORING_SPECS: &[GeneratedEntityAuthoringSpec] = &[
    GeneratedEntityAuthoringSpec {
        entity: "Note",
        kind: GeneratedAuthoringPolicyKind::Collaborative,
        rationale: "Writers edit a note concurrently: its body merges, and a change of status is decided explicitly.",
        mutations: &[NOTE_CREATE_MUTATION, NOTE_IMPORT_LORO_UPDATE_MUTATION],
        content_mutation: Some(NOTE_IMPORT_LORO_UPDATE_MUTATION),
        planning_mutations: &[],
        command_mutations: &[],
        lifecycle_mutations: &[NOTE_CREATE_MUTATION],
        session_mnemonic_key: Some("notes.session.drafts"),
        conflict_policy: Some(GeneratedAuthoringConflictPolicy::GeneratedFieldPolicy),
    },
];

pub const COLLABORATION_DEFINITION_VERSION: u32 = 1;
pub const COLLABORATION_MINIMUM_READER_VERSION: u32 = 1;
pub const COLLABORATION_MINIMUM_WRITER_VERSION: u32 = 1;

pub static NOTE_COLLABORATION_FIELDS: &[GeneratedCollaborationFieldSpec] = &[
    GeneratedCollaborationFieldSpec {
        path: "note_id",
        storage_kind: GeneratedCollaborationStorageKind::DerivedIdentity,
        container: None,
        container_template: None,
        key: None,
        identity_path: None,
        identity_variable: None,
        order_container: None,
        item_container_template: None,
        metadata_container: None,
        metadata_container_template: None,
        metadata_key: None,
        codec: GeneratedCollaborationValueCodec::Identity,
        value_schema: None,
        required: true,
        conflict: GeneratedCollaborationConflict::Immutable,
    },
    GeneratedCollaborationFieldSpec {
        path: "etag",
        storage_kind: GeneratedCollaborationStorageKind::DerivedRevision,
        container: None,
        container_template: None,
        key: None,
        identity_path: None,
        identity_variable: None,
        order_container: None,
        item_container_template: None,
        metadata_container: None,
        metadata_container_template: None,
        metadata_key: None,
        codec: GeneratedCollaborationValueCodec::String,
        value_schema: None,
        required: true,
        conflict: GeneratedCollaborationConflict::Immutable,
    },
    GeneratedCollaborationFieldSpec {
        path: "title",
        storage_kind: GeneratedCollaborationStorageKind::Scalar,
        container: Some("note"),
        container_template: None,
        key: Some("title"),
        identity_path: None,
        identity_variable: None,
        order_container: None,
        item_container_template: None,
        metadata_container: None,
        metadata_container_template: None,
        metadata_key: None,
        codec: GeneratedCollaborationValueCodec::String,
        value_schema: None,
        required: true,
        conflict: GeneratedCollaborationConflict::LastWriterWins,
    },
    GeneratedCollaborationFieldSpec {
        path: "body",
        storage_kind: GeneratedCollaborationStorageKind::Text,
        container: Some("body"),
        container_template: None,
        key: None,
        identity_path: None,
        identity_variable: None,
        order_container: None,
        item_container_template: None,
        metadata_container: None,
        metadata_container_template: None,
        metadata_key: None,
        codec: GeneratedCollaborationValueCodec::String,
        value_schema: None,
        required: true,
        conflict: GeneratedCollaborationConflict::Merge,
    },
    GeneratedCollaborationFieldSpec {
        path: "status",
        storage_kind: GeneratedCollaborationStorageKind::Scalar,
        container: Some("note"),
        container_template: None,
        key: Some("status"),
        identity_path: None,
        identity_variable: None,
        order_container: None,
        item_container_template: None,
        metadata_container: None,
        metadata_container_template: None,
        metadata_key: None,
        codec: GeneratedCollaborationValueCodec::String,
        value_schema: None,
        required: true,
        conflict: GeneratedCollaborationConflict::Explicit,
    },
];

pub static NOTE_COLLABORATION_SPEC: GeneratedCollaborationEntitySpec =
    GeneratedCollaborationEntitySpec {
        name: "Note",
        id_field: "note_id",
        substrate: "loro",
        schema_version: 1,
        migration_ids: &["note-loro-layout-v1"],
        authoring_projection: NOTES_AUTHORING_STATE_PROJECTION,
        import_mutation: NOTE_IMPORT_LORO_UPDATE_MUTATION,
        root_container: "note",
        fields: NOTE_COLLABORATION_FIELDS,
    };

pub static GENERATED_COLLABORATION_SPECS: &[GeneratedCollaborationEntitySpec] =
    &[NOTE_COLLABORATION_SPEC];

pub fn generated_collaboration_spec(
    entity: &str,
) -> Option<&'static GeneratedCollaborationEntitySpec> {
    GENERATED_COLLABORATION_SPECS
        .iter()
        .find(|spec| spec.name == entity)
}
