//! SPDX-License-Identifier: MIT
//!
//! Generated by `cargo run -p clerkenwell-codegen -- --config examples/notes/clerkenwell-codegen.json`.
//! Do not edit this file by hand.

pub use clerkenwell_schema::{
    ActorKind, GeneratedAuthoringPolicyKind, GeneratedCollaborationConflict,
    GeneratedCollaborationEntitySpec, GeneratedCollaborationFieldSpec,
    GeneratedCollaborationStorageKind, GeneratedCollaborationValueCodec,
    GeneratedEntityAuthoringSpec, GeneratedMaterializationPlan, GeneratedMutationSpec,
    GeneratedProjectionSpec, GeneratedRemoveMode, GeneratedSnapshotMode, GeneratedWriterConflict,
};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq, Eq)]
pub enum NoteDocumentStatus {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "review")]
    Review,
    #[serde(rename = "published")]
    Published,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq, Eq)]
pub enum ReplicaUpdateParamsExchangeMode {
    #[serde(rename = "incremental")]
    Incremental,
    #[serde(rename = "bootstrap")]
    Bootstrap,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq, Eq)]
pub enum AuthoringStateExchangeModes {
    #[serde(rename = "incremental")]
    Incremental,
    #[serde(rename = "bootstrap")]
    Bootstrap,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq, Eq)]
pub enum AuthoringStatePatchKind {
    #[serde(rename = "replace")]
    Replace,
    #[serde(rename = "remove")]
    Remove,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoteDocument {
    pub note_id: String,
    pub etag: String,
    #[schemars(length(min = 1))]
    pub title: String,
    pub body: String,
    pub status: NoteDocumentStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoteCreateParams {
    #[schemars(length(min = 1))]
    pub title: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoteMutationResult {
    pub note_id: String,
    pub etag: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ReplicaUpdateParams {
    pub note_id: String,
    #[schemars(length(min = 1))]
    pub operation_id: String,
    pub exchange_mode: ReplicaUpdateParamsExchangeMode,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_frontier_base64: Option<String>,
    #[schemars(length(min = 1))]
    pub update_base64: String,
    pub peer_nonces: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub intent: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ReplicaUpdateResult {
    pub note_id: String,
    pub etag: String,
    pub accepted_frontier_base64: String,
    pub missing_update_base64: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct AuthoringState {
    pub schema_version: i64,
    pub accepted_frontier_base64: String,
    pub update_base64: String,
    pub etag: String,
    pub exchange_modes: Vec<AuthoringStateExchangeModes>,
    pub peer_block: AuthoringPeerBlock,
    pub replaces_held: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct AuthoringStatePatch {
    pub kind: AuthoringStatePatchKind,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<AuthoringState>,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct AuthoringPeerBlock {
    pub nonce: String,
    pub base: String,
    pub index_bits: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoteAuthoringParams {
    pub note_id: String,
}

pub const NOTE_ENTITY: &str = "Note";

pub const NOTES_AUTHORING_STATE_PROJECTION: &str = "notes.authoringState";

pub const NOTE_CREATE_MUTATION: &str = "note.create";
pub const NOTE_IMPORT_UPDATE_MUTATION: &str = "note.importUpdate";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ProjectionName {
    NotesAuthoringState,
}

#[rustfmt::skip]
impl ProjectionName {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::NotesAuthoringState => {
                NOTES_AUTHORING_STATE_PROJECTION
            },
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            NOTES_AUTHORING_STATE_PROJECTION => {
                Some(Self::NotesAuthoringState)
            },
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MutationName {
    NoteCreate,
    NoteImportUpdate,
}

#[rustfmt::skip]
impl MutationName {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::NoteCreate => {
                NOTE_CREATE_MUTATION
            },
            Self::NoteImportUpdate => {
                NOTE_IMPORT_UPDATE_MUTATION
            },
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            NOTE_CREATE_MUTATION => {
                Some(Self::NoteCreate)
            },
            NOTE_IMPORT_UPDATE_MUTATION => {
                Some(Self::NoteImportUpdate)
            },
            _ => None,
        }
    }
}

pub const ENTITY_NAMES: &[&str] = &["Note"];
pub const PROJECTION_NAMES: &[&str] = &["notes.authoringState"];
pub const MUTATION_NAMES: &[&str] = &["note.create", "note.importUpdate"];

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "projection", content = "value", deny_unknown_fields)]
#[allow(clippy::large_enum_variant)]
pub enum ProjectionTransportSnapshot {
    #[serde(rename = "notes.authoringState")]
    NotesAuthoringState(AuthoringState),
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "projection", content = "value", deny_unknown_fields)]
#[allow(clippy::large_enum_variant)]
pub enum ProjectionTransportPatch {
    #[serde(rename = "notes.authoringState")]
    NotesAuthoringState(AuthoringStatePatch),
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "mutation", content = "value", deny_unknown_fields)]
#[allow(clippy::large_enum_variant)]
pub enum ProjectionTransportMutationResult {
    #[serde(rename = "note.create")]
    NoteCreate(NoteMutationResult),
    #[serde(rename = "note.importUpdate")]
    NoteImportUpdate(ReplicaUpdateResult),
}

impl ProjectionTransportMutationResult {
    pub const fn mutation_name(&self) -> MutationName {
        match self {
            Self::NoteCreate(_) => MutationName::NoteCreate,
            Self::NoteImportUpdate(_) => MutationName::NoteImportUpdate,
        }
    }
}

pub static GENERATED_PROJECTION_SPECS: &[GeneratedProjectionSpec] = &[GeneratedProjectionSpec {
    name: NOTES_AUTHORING_STATE_PROJECTION,
    depends_on: &["Note"],
    materialization: GeneratedMaterializationPlan::ReplaceOrRemove {
        snapshot_mode: GeneratedSnapshotMode::Field("state"),
        snapshot_omit_fields: &[],
        remove_mode: GeneratedRemoveMode::NullSnapshot,
        update_fields: None,
    },
}];

pub static GENERATED_MUTATION_SPECS: &[GeneratedMutationSpec] = &[
    GeneratedMutationSpec {
        name: NOTE_CREATE_MUTATION,
        touches: &["Note"],
    },
    GeneratedMutationSpec {
        name: NOTE_IMPORT_UPDATE_MUTATION,
        touches: &["Note"],
    },
];

pub static GENERATED_ENTITY_AUTHORING_SPECS: &[GeneratedEntityAuthoringSpec] =
    &[GeneratedEntityAuthoringSpec {
        entity: "Note",
        kind: GeneratedAuthoringPolicyKind::Collaborative,
        mutations: &[NOTE_CREATE_MUTATION, NOTE_IMPORT_UPDATE_MUTATION],
        planning_mutations: &[],
    }];

pub const COLLABORATION_DEFINITION_VERSION: u32 = 1;

pub static NOTE_COLLABORATION_FIELDS: &[GeneratedCollaborationFieldSpec] = &[
    GeneratedCollaborationFieldSpec {
        path: "note_id",
        storage_kind: GeneratedCollaborationStorageKind::DerivedIdentity,
        container: None,
        container_template: None,
        key: None,
        identity_path: None,
        identity_variable: None,
        order_container: None,
        item_container_template: None,
        metadata_container: None,
        metadata_container_template: None,
        metadata_key: None,
        codec: GeneratedCollaborationValueCodec::Identity,
        value_schema: None,
        required: true,
        required_in_parent: true,
        conflict: GeneratedCollaborationConflict::Immutable,
        writers: &[],
    },
    GeneratedCollaborationFieldSpec {
        path: "etag",
        storage_kind: GeneratedCollaborationStorageKind::DerivedRevision,
        container: None,
        container_template: None,
        key: None,
        identity_path: None,
        identity_variable: None,
        order_container: None,
        item_container_template: None,
        metadata_container: None,
        metadata_container_template: None,
        metadata_key: None,
        codec: GeneratedCollaborationValueCodec::String,
        value_schema: None,
        required: true,
        required_in_parent: true,
        conflict: GeneratedCollaborationConflict::Immutable,
        writers: &[],
    },
    GeneratedCollaborationFieldSpec {
        path: "title",
        storage_kind: GeneratedCollaborationStorageKind::Scalar,
        container: Some("note"),
        container_template: None,
        key: Some("title"),
        identity_path: None,
        identity_variable: None,
        order_container: None,
        item_container_template: None,
        metadata_container: None,
        metadata_container_template: None,
        metadata_key: None,
        codec: GeneratedCollaborationValueCodec::String,
        value_schema: None,
        required: true,
        required_in_parent: true,
        conflict: GeneratedCollaborationConflict::LastWriterWins,
        writers: &[],
    },
    GeneratedCollaborationFieldSpec {
        path: "body",
        storage_kind: GeneratedCollaborationStorageKind::Text,
        container: Some("body"),
        container_template: None,
        key: None,
        identity_path: None,
        identity_variable: None,
        order_container: None,
        item_container_template: None,
        metadata_container: None,
        metadata_container_template: None,
        metadata_key: None,
        codec: GeneratedCollaborationValueCodec::String,
        value_schema: None,
        required: true,
        required_in_parent: true,
        conflict: GeneratedCollaborationConflict::Merge,
        writers: &[],
    },
    GeneratedCollaborationFieldSpec {
        path: "status",
        storage_kind: GeneratedCollaborationStorageKind::Scalar,
        container: Some("note"),
        container_template: None,
        key: Some("status"),
        identity_path: None,
        identity_variable: None,
        order_container: None,
        item_container_template: None,
        metadata_container: None,
        metadata_container_template: None,
        metadata_key: None,
        codec: GeneratedCollaborationValueCodec::String,
        value_schema: None,
        required: true,
        required_in_parent: true,
        conflict: GeneratedCollaborationConflict::Explicit,
        writers: &[GeneratedWriterConflict {
            kind: ActorKind::Agent,
            conflict: GeneratedCollaborationConflict::Immutable,
        }],
    },
];

pub static NOTE_COLLABORATION_SPEC: GeneratedCollaborationEntitySpec =
    GeneratedCollaborationEntitySpec {
        name: "Note",
        id_field: "note_id",
        schema_version: 1,
        authoring_projection: NOTES_AUTHORING_STATE_PROJECTION,
        authoring_document: None,
        authoring_store_params: &[],
        import_mutation: NOTE_IMPORT_UPDATE_MUTATION,
        root_container: "note",
        fields: NOTE_COLLABORATION_FIELDS,
    };

pub static GENERATED_COLLABORATION_SPECS: &[GeneratedCollaborationEntitySpec] =
    &[NOTE_COLLABORATION_SPEC];

pub fn generated_collaboration_spec(
    entity: &str,
) -> Option<&'static GeneratedCollaborationEntitySpec> {
    GENERATED_COLLABORATION_SPECS
        .iter()
        .find(|spec| spec.name == entity)
}
